---
# tasks file for ansible-role-pihole-podman

- name: "Copy pihole data dir"
  copy:
    src: "data"
    dest: "{{ base_dir }}/pihole/"

- name: "Copy pihole dnsmasq dir"
  copy:
    src: "dnsmasq"
    dest: "{{ base_dir }}/pihole/"

- name: "Run pihole container"
  containers.podman.podman_container:
    name: "pihole"
    image: "docker.io/pihole/pihole:{{ image_tag }}"
    state: "started"
    restart_policy: "no"
    recreate: no
    tty: no
    detach: yes
    # cap_add:
    #   - "CAP_NET_BIND_SERVICE"
    env:
      TZ: "{{ time_zone }}"
      SERVERIP: "{{ server_ip }}"
      WEBPASSWORD: "{{ web_password }}"
    ports:
      - "7654:80"
      - "53:53/tcp"
      - "53:53/udp"
    volume:
      - "{{ base_dir }}/pihole/data:/etc/pihole:Z"
      - "{{ base_dir }}/pihole/dnsmasq:/etc/dnsmasq:Z"
